# Generated by Django 4.0.6 on 2022-07-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0003_carteira_time_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteira',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='time',
            name='id_time',
        ),
    ]
