# Generated by Django 4.0.6 on 2022-07-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0004_remove_carteira_id_usuario_remove_time_id_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteira',
            name='id_time',
        ),
    ]
