# Generated by Django 4.0.6 on 2022-07-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0005_remove_carteira_id_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carteira',
            old_name='qyde_acoes',
            new_name='qtde_acoes',
        ),
    ]
