# Generated by Django 4.0.6 on 2022-07-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0006_rename_qyde_acoes_carteira_qtde_acoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteira',
            name='id',
        ),
        migrations.AddField(
            model_name='carteira',
            name='id_time',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='AAA', to='Futex.time'),
        ),
        migrations.AddField(
            model_name='carteira',
            name='id_usuario',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
