# Generated by Django 4.0.6 on 2022-07-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0007_remove_carteira_id_carteira_id_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Carteira',
        ),
    ]
