# Generated by Django 4.0.6 on 2022-07-19 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0008_cliente_delete_carteira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde_acoes', models.IntegerField()),
                ('id_cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_cliente_carteira', to='Futex.cliente')),
                ('id_time', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_time_carteira', to='Futex.time')),
            ],
        ),
    ]
