# Generated by Django 4.0.6 on 2022-07-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0010_alter_cliente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
