# Generated by Django 4.0.6 on 2022-07-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0013_alter_carteira_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='estado',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='time',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
