# Generated by Django 4.0.6 on 2022-07-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0014_alter_time_estado_alter_time_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='estado',
            field=models.CharField(max_length=2),
        ),
    ]
