# Generated by Django 4.0.6 on 2022-08-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0017_cliente_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('id_time', models.IntegerField()),
                ('tipo_operacao', models.IntegerField()),
                ('qtde_acoes', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
    ]
