# Generated by Django 4.0.6 on 2022-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0025_remove_cliente_id_alter_cliente_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
