# Generated by Django 4.0.6 on 2022-08-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0027_remove_carteira_id_cliente_carteira_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='id_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_cliente_carteira', to='Futex.cliente'),
        ),
    ]
