# Generated by Django 4.0.6 on 2022-08-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0028_alter_carteira_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='id',
        ),
        migrations.AddField(
            model_name='time',
            name='id_time',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='carteira',
            name='id_cliente',
            field=models.ManyToManyField(default=0, to='Futex.cliente'),
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='id_time',
        ),
        migrations.AddField(
            model_name='carteira',
            name='id_time',
            field=models.ManyToManyField(default=0, to='Futex.time'),
        ),
    ]
