# Generated by Django 4.0.6 on 2022-08-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0029_remove_time_id_time_id_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='id_cliente',
            field=models.ManyToManyField(to='Futex.cliente'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='id_time',
            field=models.ManyToManyField(to='Futex.time'),
        ),
    ]
