# Generated by Django 4.0.6 on 2022-08-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0030_alter_carteira_id_cliente_alter_carteira_id_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteira',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='carteira',
            name='id_cliente',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='id_time',
        ),
        migrations.AddField(
            model_name='carteira',
            name='id_time',
            field=models.IntegerField(default=0),
        ),
    ]
