# Generated by Django 4.0.6 on 2022-08-08 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Futex', '0034_alter_carteira_id_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico_Cliente',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='id_time',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='carteira',
            name='id_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_carteira_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='time',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='nome',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
