# Generated by Django 4.0.6 on 2022-08-08 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Futex', '0036_rename_id_time_id_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='id_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='id_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_carteira_time', to='Futex.time'),
        ),
        migrations.AlterField(
            model_name='time',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='time',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
