# Generated by Django 4.0.6 on 2022-08-16 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0039_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='id_time_casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_time_casa', to='Futex.time'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='id_time_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_time_visitante', to='Futex.time'),
        ),
    ]
