# Generated by Django 4.0.6 on 2022-08-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0041_alter_partida_id_partida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VITORIA_CASA', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('VITORIA_FORA', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('EMPATE_CASA', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('EMPATE_FORA', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('DERROTA_CASA', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('DERROTA_FORA', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
    ]
