# Generated by Django 4.0.6 on 2022-08-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0042_parametros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametros',
            name='id',
        ),
        migrations.AddField(
            model_name='parametros',
            name='ID_PARAMETRO',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
