# Generated by Django 4.0.6 on 2022-08-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0044_alter_partida_placar_time_casa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico_cliente',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
