# Generated by Django 4.0.6 on 2022-08-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0045_historico_cliente_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('Posicao', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('saldo', models.IntegerField()),
            ],
        ),
    ]
