# Generated by Django 4.0.6 on 2022-08-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Futex', '0046_ranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
